apiVersion: v1
kind: Pod
metadata:
  name: testpod
  namespace: default
  labels:
    plugin: ssh-node
spec:
  containers:
    - name: ssh-node
      image: python
      imagePullPolicy: IfNotPresent
      command: ["chroot", "/"]
      # command: ["/bin/bash", "-i"]
      tty: true
      stdin: true
      stdinOnce: true
      securityContext:
        privileged: true
      volumeMounts:
        - name: host
          mountPath: /host
      resources: {}
      env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
  volumes:
    - name: host
      hostPath:
        path: /
  hostNetwork: true
  hostIPC: true
  hostPID: true
  restartPolicy: Never
  tolerations:
    - operator: "Exists"
